[package]
name = "cargo-c"
version = "0.5.1"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
description = "Helper program to build and install c-like libraries"
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "http://github.com/lu-zero/cargo-c"
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
keywords = ["cargo", "cdylib"]
default-run = "cargo-cbuild"


[[bin]]
name = "cargo-cinstall"
path = "src/main.rs"

[[bin]]
name = "cargo-cbuild"
path = "src/main.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3.0"
cargo_metadata = "0.9"
structopt = "0.3"
regex = "1"
cbindgen = "0.12"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
